name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    name: ${{ matrix.name || 'Build & Test' }} (Swift ${{ matrix.swift }}, ${{ matrix.platform-name || matrix.platform }})
    runs-on: ${{ matrix.macos || 'macos-latest' }}
    strategy:
      fail-fast: false
      matrix:
        swift: ['5.6']
        platform: [macOS]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: ${{ matrix.name || 'Build & Test' }}
        uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          swift: ~${{ matrix.swift }}
          code-coverage: true
          warnings-as-errors: true
      - name: Install uploader deps
        run: npm install
      - name: Run uploader (with proj)
        run: ./dist/bin/codecov.js -t 47eaddcf-59e4-447f-8e64-18897dadd8ba --xs --xsp CombineCloudKit
      - name: Run uploader (without proj)
        run: ./dist/bin/codecov.js -t 47eaddcf-59e4-447f-8e64-18897dadd8ba --xs
