name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    name: ${{ matrix.name || 'Build & Test' }} (Swift ${{ matrix.swift }}, ${{ matrix.platform-name || matrix.platform }})
    runs-on: ${{ matrix.macos || 'macos-latest' }}
    strategy:
      fail-fast: false
      matrix:
        swift: ['5.6', '5.7']
        platform: [macOS, iOS]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: ${{ matrix.name || 'Build & Test' }}
        uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          swift: ~${{ matrix.swift }}
          code-coverage: true
          warnings-as-errors: true
      - name: Coverage
        if: ${{ matrix.name != 'Build' }}
        uses: codecov/codecov-action@v1
        with:
          token: 47eaddcf-59e4-447f-8e64-18897dadd8ba
          flags: ${{ matrix.platform }},swift${{ matrix.swift }}
